2024-07-12 00:50:51,920 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 00:50:51,921 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 00:50:51,976 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 00:50:51,995 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 00:50:51,995 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 00:50:51,996 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 00:50:52,881 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 00:50:52,881 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 00:50:52,935 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 00:50:52,951 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 00:50:52,952 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 00:50:52,952 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 00:51:32,199 INFO Homepage accessed: /home/frank/original_virtual_doctor/routes/public_routes.py 18
2024-07-12 00:51:49,194 INFO Homepage accessed: /home/frank/original_virtual_doctor/routes/public_routes.py 18
2024-07-12 00:51:58,811 INFO prescription retrieved from prescriptions database: /home/frank/original_virtual_doctor/routes/user_routes.py 444
2024-07-12 00:51:58,820 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 483
2024-07-12 00:52:24,214 INFO Homepage accessed: /home/frank/original_virtual_doctor/routes/public_routes.py 18
2024-07-12 00:53:24,037 INFO Logging setup successfully: /home/frank/original_virtual_doctor/app.py 28
2024-07-12 00:53:24,037 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/app.py 40
2024-07-12 00:53:24,067 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/app.py 52
2024-07-12 00:53:24,083 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/app.py 60
2024-07-12 00:53:24,083 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/app.py 73
2024-07-12 00:53:24,083 INFO App created successfully: /home/frank/original_virtual_doctor/app.py 83
2024-07-12 00:59:38,613 INFO Prescription retrieved from redis: /home/frank/original_virtual_doctor/routes/user_routes.py 451
2024-07-12 00:59:38,618 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 483
2024-07-12 14:24:44,280 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 14:24:44,280 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 14:24:44,749 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 14:24:44,767 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 14:24:44,767 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 14:24:44,768 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 14:24:45,797 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 14:24:45,798 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 14:24:45,857 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 14:24:45,873 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 14:24:45,874 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 14:24:45,874 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 14:25:13,260 INFO Homepage accessed: /home/frank/original_virtual_doctor/routes/public_routes.py 18
2024-07-12 14:26:02,647 INFO Homepage accessed: /home/frank/original_virtual_doctor/routes/public_routes.py 18
2024-07-12 14:27:37,766 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 421
2024-07-12 14:27:39,296 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 483
2024-07-12 14:28:06,970 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 421
2024-07-12 14:28:06,977 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 483
2024-07-12 14:28:23,513 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 421
2024-07-12 14:28:23,520 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 483
2024-07-12 14:57:37,354 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 421
2024-07-12 14:57:37,361 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 483
2024-07-12 15:46:25,976 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 421
2024-07-12 15:46:25,985 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 483
2024-07-12 15:47:03,622 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 421
2024-07-12 15:47:03,630 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 483
2024-07-12 15:53:49,755 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 421
2024-07-12 15:53:49,762 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 483
2024-07-12 15:55:22,092 INFO Homepage accessed: /home/frank/original_virtual_doctor/routes/public_routes.py 18
2024-07-12 15:55:51,943 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 421
2024-07-12 15:55:51,949 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 483
2024-07-12 15:58:21,426 INFO Homepage accessed: /home/frank/original_virtual_doctor/routes/public_routes.py 18
2024-07-12 15:58:21,830 INFO Homepage accessed: /home/frank/original_virtual_doctor/routes/public_routes.py 18
2024-07-12 15:58:25,789 INFO Homepage accessed: /home/frank/original_virtual_doctor/routes/public_routes.py 18
2024-07-12 15:59:01,747 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 421
2024-07-12 15:59:01,751 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 483
2024-07-12 15:59:17,753 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 421
2024-07-12 15:59:17,765 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 483
2024-07-12 15:59:20,815 INFO Homepage accessed: /home/frank/original_virtual_doctor/routes/public_routes.py 18
2024-07-12 16:03:07,483 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 16:03:07,483 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 16:03:07,700 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 16:03:07,722 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 16:03:07,723 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 16:03:07,723 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 16:03:17,178 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 423
2024-07-12 16:03:17,269 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 485
2024-07-12 16:04:17,289 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 16:04:17,290 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 16:04:17,353 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 16:04:17,371 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 16:04:17,372 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 16:04:17,372 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 16:05:25,737 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 16:05:25,737 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 16:05:25,799 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 16:05:25,817 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 16:05:25,818 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 16:05:25,818 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 16:06:55,318 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 423
2024-07-12 16:06:55,399 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 485
2024-07-12 16:07:05,867 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 423
2024-07-12 16:07:05,873 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 485
2024-07-12 17:45:40,272 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 423
2024-07-12 17:45:40,278 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 485
2024-07-12 17:46:14,173 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 423
2024-07-12 17:46:14,181 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 485
2024-07-12 17:46:21,029 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 423
2024-07-12 17:46:21,035 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 485
2024-07-12 17:49:20,294 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 17:49:20,294 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 17:49:20,366 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 17:49:20,385 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 17:49:20,386 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 17:49:20,386 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 17:51:02,053 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 17:51:02,053 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 17:51:02,124 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 17:51:02,143 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 17:51:02,144 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 17:51:02,144 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 17:53:20,174 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 423
2024-07-12 17:53:20,266 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 485
2024-07-12 17:53:41,838 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 423
2024-07-12 17:53:41,844 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 485
2024-07-12 17:55:56,373 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 423
2024-07-12 17:55:56,381 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 485
2024-07-12 17:57:35,070 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 17:57:35,070 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 17:57:35,138 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 17:57:35,158 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 17:57:35,158 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 17:57:35,159 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 17:58:19,844 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 17:58:19,845 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 17:58:19,907 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 17:58:19,927 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 17:58:19,928 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 17:58:19,928 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 17:58:54,271 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 17:58:54,271 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 17:58:54,337 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 17:58:54,359 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 17:58:54,359 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 17:58:54,359 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 17:59:02,473 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 17:59:02,473 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 17:59:02,537 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 17:59:02,557 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 17:59:02,557 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 17:59:02,557 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 18:13:59,715 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 18:13:59,715 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 18:13:59,786 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 18:13:59,810 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 18:13:59,810 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 18:13:59,810 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 18:15:08,735 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 423
2024-07-12 18:15:08,849 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 485
2024-07-12 18:15:43,095 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 423
2024-07-12 18:15:43,102 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 485
2024-07-12 19:24:24,465 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 423
2024-07-12 19:24:24,485 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 485
2024-07-12 19:37:00,765 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 19:37:00,766 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 19:37:00,852 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 19:37:00,869 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 19:37:00,869 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 19:37:00,869 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 19:37:01,728 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 19:37:01,728 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 19:37:01,785 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 19:37:01,801 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 19:37:01,802 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 19:37:01,802 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 19:37:21,536 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 423
2024-07-12 19:37:21,623 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 485
2024-07-12 19:37:35,946 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 423
2024-07-12 19:37:35,952 INFO Prescription searched in database: /home/frank/original_virtual_doctor/routes/user_routes.py 485
2024-07-12 19:48:41,416 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 19:48:41,416 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 19:48:41,501 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 19:48:41,518 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 19:48:41,519 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 19:48:41,519 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 19:49:09,011 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 19:49:09,011 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 19:49:09,072 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 19:49:09,092 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 19:49:09,092 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 19:49:09,093 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 19:52:02,274 INFO Homepage accessed: /home/frank/original_virtual_doctor/routes/public_routes.py 18
2024-07-12 19:52:20,060 INFO Homepage accessed: /home/frank/original_virtual_doctor/routes/public_routes.py 18
2024-07-12 19:52:29,076 INFO Homepage accessed: /home/frank/original_virtual_doctor/routes/public_routes.py 18
2024-07-12 19:59:47,059 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 19:59:47,059 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 19:59:47,132 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 19:59:47,160 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 19:59:47,161 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 19:59:47,161 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 20:00:01,951 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 20:00:01,951 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 20:00:02,023 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 20:00:02,051 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 20:00:02,051 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 20:00:02,051 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 20:17:45,384 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 20:17:45,385 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 20:17:45,460 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 20:17:45,480 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 20:17:45,480 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 20:17:45,481 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 20:18:19,227 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 20:18:19,227 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 20:18:19,292 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 20:18:19,312 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 20:18:19,312 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 20:18:19,312 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 20:20:51,326 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 20:20:51,326 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 20:20:51,387 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 20:20:51,410 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 20:20:51,410 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 20:20:51,410 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 20:58:17,809 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 20:58:17,810 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 20:58:24,454 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 20:58:24,538 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 20:58:24,540 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 20:58:24,541 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 20:59:52,086 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 20:59:52,086 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 20:59:52,299 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 20:59:52,342 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 20:59:52,342 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 20:59:52,343 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 21:01:00,510 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 21:01:00,510 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 21:01:00,830 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 21:01:00,874 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 21:01:00,875 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 21:01:00,875 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 22:46:05,462 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 22:46:05,462 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 22:46:05,669 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 22:46:05,692 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 22:46:05,692 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 22:46:05,692 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 22:46:06,657 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 22:46:06,658 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 22:46:06,917 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 22:46:06,941 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 22:46:06,941 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 22:46:06,942 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 22:47:58,210 INFO Homepage accessed: /home/frank/original_virtual_doctor/routes/public_routes.py 18
2024-07-12 22:49:26,184 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 424
2024-07-12 22:49:26,722 ERROR An error occured while storing order details to pharm_orders: /home/frank/original_virtual_doctor/routes/user_routes.py 474
Traceback (most recent call last):
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'price' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frank/original_virtual_doctor/routes/user_routes.py", line 472, in pharm_search
    db.session.commit()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1421, in execute
    return meth(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1849, in _execute_context
    return self._exec_single_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'price' in 'field list'")
[SQL: INSERT INTO pharm_orders (order_uuid, presc, price, status, user_id) VALUES (%(order_uuid)s, %(presc)s, %(price)s, %(status)s, %(user_id)s)]
[parameters: {'order_uuid': '5da09d53-7a68-4801-a204-5ac6d0e11a5e', 'presc': '[{"med_name": "Jj", "dosage": "20 kg"}]', 'price': None, 'status': 'incomplete', 'user_id': None}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-07-12 22:49:27,381 ERROR An error occured when searching for meds in the databaseThis Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.OperationalError) (1054, "Unknown column 'price' in 'field list'")
[SQL: INSERT INTO pharm_orders (order_uuid, presc, price, status, user_id) VALUES (%(order_uuid)s, %(presc)s, %(price)s, %(status)s, %(user_id)s)]
[parameters: {'order_uuid': '5da09d53-7a68-4801-a204-5ac6d0e11a5e', 'presc': '[{"med_name": "Jj", "dosage": "20 kg"}]', 'price': None, 'status': 'incomplete', 'user_id': None}]
(Background on this error at: https://sqlalche.me/e/20/e3q8) (Background on this error at: https://sqlalche.me/e/20/7s2a): /home/frank/original_virtual_doctor/routes/user_routes.py 504
2024-07-12 22:52:24,255 INFO Logging setup successfully: /home/frank/original_virtual_doctor/./app.py 28
2024-07-12 22:52:24,255 INFO DataBase set up successfully: /home/frank/original_virtual_doctor/./app.py 40
2024-07-12 22:52:24,489 INFO Migrations set up successfully: /home/frank/original_virtual_doctor/./app.py 52
2024-07-12 22:52:24,506 INFO Blueprints registered successfully: /home/frank/original_virtual_doctor/./app.py 60
2024-07-12 22:52:24,507 INFO Mail service setup successfully: /home/frank/original_virtual_doctor/./app.py 73
2024-07-12 22:52:24,507 INFO App created successfully: /home/frank/original_virtual_doctor/./app.py 83
2024-07-12 22:52:31,545 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 424
2024-07-12 22:52:31,633 ERROR An error occured while storing order details to pharm_orders: /home/frank/original_virtual_doctor/routes/user_routes.py 474
Traceback (most recent call last):
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'price' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frank/original_virtual_doctor/routes/user_routes.py", line 472, in pharm_search
    db.session.commit()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1421, in execute
    return meth(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1849, in _execute_context
    return self._exec_single_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'price' in 'field list'")
[SQL: INSERT INTO pharm_orders (order_uuid, presc, price, status, user_id) VALUES (%(order_uuid)s, %(presc)s, %(price)s, %(status)s, %(user_id)s)]
[parameters: {'order_uuid': '1585e39c-0ce7-40dc-9ee8-10443813dbb5', 'presc': '[{"med_name": "Jj", "dosage": "20 kg"}]', 'price': None, 'status': 'incomplete', 'user_id': None}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-07-12 22:52:31,641 ERROR An error occured when searching for meds in the databaseThis Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.OperationalError) (1054, "Unknown column 'price' in 'field list'")
[SQL: INSERT INTO pharm_orders (order_uuid, presc, price, status, user_id) VALUES (%(order_uuid)s, %(presc)s, %(price)s, %(status)s, %(user_id)s)]
[parameters: {'order_uuid': '1585e39c-0ce7-40dc-9ee8-10443813dbb5', 'presc': '[{"med_name": "Jj", "dosage": "20 kg"}]', 'price': None, 'status': 'incomplete', 'user_id': None}]
(Background on this error at: https://sqlalche.me/e/20/e3q8) (Background on this error at: https://sqlalche.me/e/20/7s2a): /home/frank/original_virtual_doctor/routes/user_routes.py 504
2024-07-12 22:52:35,218 INFO Uploaded prescription retrieved: /home/frank/original_virtual_doctor/routes/user_routes.py 424
